---
# Main tasks file for setk8s_ssh_env role
- name: Validate Required Variables
  ansible.builtin.assert:
    that:
      - cluster_adm_kube_dir is defined
      - cluster_adm_kube_dir | string | length > 0
      - cluster.name is defined
      - cluster.name | string | length > 0
    fail_msg: "Required variables are not set. Please ensure all required variables are defined."
    success_msg: "All required variables are properly set"

- name: Configure cluster variables
  ansible.builtin.include_tasks:
    file: cluster_variables.yml
  tags:
    - always
    - cluster_setup
    - variables

- name: Include tasks from pull_kubeconfig_vault.yml
  ansible.builtin.include_tasks:
    file: pull_kubeconfig_vault.yml
  when: >
    not (cluster_adm_kube_dir is defined and
         cluster_adm_kube_dir | length > 0 and
         lookup('ansible.builtin.fileglob', cluster_adm_kube_dir + '/' + cluster.name) | length > 0)
  tags:
    - always
    - vault
    - kubeconfig
    - cluster_setup
