---
# setup_cluster_pxbkup.yml
#
# This playbook sets up a Kubernetes cluster with Portworx Backup integration.
# It handles the following tasks:
# - Retrieves Vault configuration from inventory
# - Authenticates with Px-Backup and obtains token
# - Verifies and updates schedule policies
# - Creates necessary service accounts and roles
# - Registers the cluster with Px-Backup
#
# Requirements:
# - Vault access configured
# - Valid kubeconfig
# - Px-Backup credentials
#
# Author: Your Name
# Last Updated: 2025-01-30

- name: Setup Kubernetes Service Account with Vault Integration
  hosts: localhost
  gather_facts: false

  vars:
    ansible_log_path: "{{ playbook_dir }}/logs/setup_cluster_pxbkup.log"

  pre_tasks:
    - name: Ensure log directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/logs"
        state: directory
        mode: '0750'
      delegate_to: localhost

    - name: Set error handling block
      ansible.builtin.set_fact:
        error_handling: |
          block:
            - name: Include task
              ansible.builtin.include_tasks: "{{ include_file }}"
          rescue:
            - name: Log error
              ansible.builtin.debug:
                msg: "Error executing {{ include_file }}: {{ ansible_failed_result }}"
              when: ansible_failed_result is defined
            - ansible.builtin.fail:
                msg: "Failed to execute {{ include_file }}"

  roles:
    - role: setup_cluster_pxbkup
