---
all:
  hosts:
    server1:
      ansible_host: 192.168.100.4
    server2:
      ansible_host: 192.168.100.5

ungrouped:
  hosts:
    server1:
      ansible_host: 192.168.100.4
    server2:
      ansible_host: 192.168.100.5

