---

- name: Login and fetch Px-Backup token
  ansible.builtin.include_tasks: "auth.yaml"

- name: Create clusters
  block:
    - name: Create cluster
      purepx.px_backup.cluster:
        operation: CREATE
        api_url: "{{ px_backup_api_url }}"
        token: "{{ px_backup_token }}"
        name: "{{ item.name }}"
        org_id: "{{ org_id | default('default') }}"
        cloud_type: "{{ item.cloud_type }}"
        kubeconfig: "{{ lookup('file', item.kubeconfig) }}"
        cloud_credential_ref: "{{ item.cloud_credential_ref | default(omit) }}"
        platform_credential_ref: "{{ item.platform_credential_ref | default(omit) }}"
        px_config: "{{ item.px_config | default(omit) }}"
        service_token: "{{ item.service_token | default(omit) }}"
        validate_certs: "{{ item.validate_certs | default(true) }}"
      loop: "{{ clusters }}"
      register: cluster_result
      loop_control:
        label: "{{ item.name }}"

  rescue:
    - name: Display error details
      ansible.builtin.debug:
        msg: "Failed to create cluster: {{ cluster_result.results | selectattr('failed', 'true') | map(attribute='msg') | list }}"
      when: cluster_result is defined and cluster_result.results is defined

    - name: Fail with error message
      ansible.builtin.fail:
        msg: "Failed to create clusters. See above for details."

- name: Display creation results
  ansible.builtin.debug:
    msg:
      - "Successfully created clusters:"
      - "Created locations: {{ cluster_result.results | map(attribute='item.name') | list }}"
      - "Changed status: {{ cluster_result.results | map(attribute='changed') | list }}"
  when:
    - cluster_result is defined
    - cluster_result.results is defined
    - (cluster_result.results | selectattr('failed', 'defined') | selectattr('failed', 'true') | list | length) == 0
