---
- name: "Get Vault configuration from inventory"
  ansible.builtin.uri:
    url: "https://inventory.com/v2/inventory/{{ inventory_id }}"
    method: GET
    return_content: true
    validate_certs: "{{ validate_certs | default(true) }}"
    headers:
      Accept: "application/json"
  register: inventory_response

- name: "Set Vault configuration facts"
  ansible.builtin.set_fact:
    vault_address: "{{ inventory_response.json | community.general.json_query('kubernetes_platform.secrets_management.platform_vault[0].address') }}"
    vault_namespace: "{{ inventory_response.json | community.general.json_query('kubernetes_platform.secrets_management.platform_vault[0].namespace') }}"
    vault_default_path_full: "{{ inventory_response.json | community.general.json_query('kubernetes_platform.secrets_management.platform_vault[0].default_path') }}"

- name: "Set Vault mount point and clean default path"
  ansible.builtin.set_fact:
    vault_mount_point: "{{ vault_default_path_full.split('/')[0] }}"
    vault_default_path: "{{ vault_default_path_full if not vault_default_path_full.startswith('static_secrets/') else vault_default_path_full[14:] }}"

- name: "Set required variables for createSaRole task"
  ansible.builtin.set_fact:
    vault_mount_point: "{{ vault_mount_point }}"
    vault_namespace: "{{ vault_namespace }}"
    kubeconfig_vault_path: "{{ vault_default_path }}"

- name: "Verify Vault configuration facts"
  ansible.builtin.debug:
    msg: |
      Vault Address: {{ vault_address }}
      Vault Namespace: {{ vault_namespace }}
      Vault Default Path (Full): {{ vault_default_path_full }}
      Vault Default Path (Clean): {{ vault_default_path }}
      Vault Mount Point: {{ vault_mount_point }}
      Vault Namespace: {{ vault_namespace }}
      Kubeconfig Path: {{ kubeconfig_path }}
