---
vault_token_path: "/run/secrets/vault-token"
vault_automation_prod_address: "https://vault-prod.example.com"
vault_automation_dev_address: "https://vault-dev.example.com"
vault_automation_test_address: "https://vault-test.example.com"
vault_automation_eng_address: "https://vault-eng.example.com"
vault_automation_default_namespace: "automation"
vault_automation_config_path: "kubernetes/"
vault_automation_config_mount_point: "secret"
vault_cacert_path: ""
vault_cacert_mount_path: ""
vault_cacert_namespace: "automation"
k8s_ns: "portworx"
service_account_name: "pxbackup-sa"
cluster_role_name: "pxbackup-cluster-role"
sa_role_name: "pxbackup-role"
cluster_role_binding_name: "pxbackup-cluster-rolebinding"
sa_role_binding_name: "pxbackup-rolebinding"
inventory_url: "https://inventory.example.com"
validate_certs: true
ca_cert_path: "/etc/ssl/certs/ca-certificates.crt"
cluster_adm_kube_dir: ""
