---
- name: Check_and_update
  hosts: localhost
  gather_facts: false
  vars:
    cluster_adm_kube_dir: "{{ playbook_dir | dirname }}/tmp/cache/kube_config"
    cluster: { "name":"cld-paas-d-eusw1c-4"}
    all_backup_schedules:
      - "all/pxbackup.portworx.io=4am"
      - "all/pxbackup.portworx.io=8am"
      - "all/pxbackup.portworx.io=12am"
      - "all/pxbackup.portworx.io=4pm"
      - "all/pxbackup.portworx.io=8pm"
      - "all/pxbackup.portworx.io=12pm"
    assigned_schedules: {}  # Initialize empty dictionary
    namespaces_with_pxbackup_default: []
    namespaces_using_nfs_pv: []
    namespaces_needing_all_label: []
    pv_to_ns_map: {}
    ns_to_pv_map: {}
    nfs_pvs: []
    inital_label: "pxbackup"
    namespaces_needing_schedule: []
    apply_labels: "{{ apply_labels | default(false) | bool }}"  # Default to true, can be set to false for noop mode

  tasks:

    - name: "Show Cluster"
      ansible.builtin.debug:
        msg: "Cluster {{ cluster.name }} Kube_adm_dir: {{ cluster_adm_kube_dir }}"

    # Read kubeconfig from file if it exists
    - name: Read kubeconfig from local file
      ansible.builtin.slurp:
        src: "{{ cluster_adm_kube_dir }}/{{ cluster.name }}.kubeconfig"
      register: local_kubeconfig_content
      no_log: true
      when: cluster_adm_kube_dir is defined and cluster_adm_kube_dir | length > 0 and lookup('ansible.builtin.fileglob', cluster_adm_kube_dir + '/' + cluster.name + '.kubeconfig') | length > 0

    # Set local file if found instead
    - name: Set kubeconfig from local file
      ansible.builtin.set_fact:
        kubeconfig_admin: "{{ local_kubeconfig_content.content | b64decode }}"
      no_log: true
      when: local_kubeconfig_content is defined and local_kubeconfig_content.content is defined

    - name: Get all namespaces
      kubernetes.core.k8s_info:
        api_version: v1
        kubeconfig: "{{ kubeconfig_admin | from_yaml }}"
        kind: Namespace
      register: namespaces_info

    - name: Filter namespaces with pxbackup=default label
      ansible.builtin.set_fact:
        namespaces_with_pxbackup_default: "{{ namespaces_info.resources | selectattr('metadata.labels.pxbackup', 'defined') | selectattr('metadata.labels.pxbackup', 'equalto', 'default') }}"

    - name: Initialize namespaces_needing_all_label
      ansible.builtin.set_fact:
        namespaces_needing_all_label: []

    - name: Check each namespace for missing backup schedule labels
      ansible.builtin.set_fact:
        namespaces_needing_all_label: >-
          {{
            namespaces_needing_all_label +
            [namespace.metadata.name]
          }}
      loop: "{{ namespaces_with_pxbackup_default }}"
      loop_control:
        loop_var: namespace
      when: >
        namespace.metadata.labels is defined and
        not (namespace.metadata.labels | intersect(all_backup_schedules | map('split', '=') | map('first') | list))

    - name: Display namespaces needing backup schedule
      ansible.builtin.debug:
        msg: |
          Namespaces needing backup schedule:
          {%- for ns in namespaces_needing_all_label %}
          - {{ ns }}
          {%- endfor %}

    - name: Assign random backup schedule to namespaces
      ansible.builtin.set_fact:
        assigned_schedules: "{{ assigned_schedules | default({}) | combine({item: all_backup_schedules[item | hash('sha1') | int % all_backup_schedules | length]}) }}"
      loop: "{{ namespaces_needing_all_label }}"
      loop_control:
        label: "{{ item }}"

    - name: Display assigned backup schedules
      ansible.builtin.debug:
        msg: |
          Assigned backup schedules:
          {%- for ns, schedule in assigned_schedules.items() %}

          - Namespace: {{ ns }} → Schedule: {{ schedule }}
          {%- endfor %}

    - name: Apply backup schedule labels to namespaces
      kubernetes.core.k8s:
        api_version: v1
        kubeconfig: "{{ kubeconfig_admin | from_yaml }}"
        kind: Namespace
        name: "{{ item.key }}"
        state: present
        merge_type: merge
        definition:
          metadata:
            labels:
              "{{ item.value.split('=')[0] }}": "{{ item.value.split('=')[1] }}"
      loop: "{{ assigned_schedules | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: apply_labels | bool
