---
- name: Manage Kubernetes Resources
  hosts: all
  gather_facts: false

  tasks:
    - name: Setup cluster variables
      ansible.builtin.include_role:
        name: common
        tasks_from: setup_cluster_variables.yml

    - name: Run get kubeconfig from vault
      ansible.builtin.include_role:
        name: common
        tasks_from: pull_kubeconfig_vault.yml

    - name: "Retrieve ca_certs from Vault"
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_address }}"
        path: "{{ vault_cacert_path }}"
        engine_mount_point: "{{ vault_cacert_mount_path }}"
        auth_method: token
        token: "{{ vault_token }}"
        namespace: "{{ vault_namespace }}"
        validate_certs: "{{ validate_certs }}"
        ca_cert: "{{ ca_cert_path }}"
      register: vault_cacert_response
      no_log: false

    - name: Get CA certs
      ansible.builtin.set_fact:
        prod_ca: "{{ vault_cacert_response.data.data.ProdCA }}"
        nonProd_ca: "{{ vault_cacert_response.data.data.NonProdCA }}"

    - name: "Ensure kubeconfig directory exists"
      ansible.builtin.file:
        path: "{{ outp_k8s_config_path }}"
        state: directory
        mode: '0750'

    - name: Ensure namespace exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_ns }}"

    - name: Ensure service account exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: "{{ service_account_name }}"
            namespace: "{{ k8s_ns }}"

    - name: Check if service account token exists
      ansible.builtin.set_fact:
        token_name: "{{ service_account_name }}-token"

    - name: Get existing service account token
      kubernetes.core.k8s_info:
        kubeconfig: "{{ master_kubeconfig }}"
        api_version: v1
        kind: Secret
        namespace: "{{ k8s_ns }}"
        name: "{{ token_name }}"
      register: existing_token
      no_log: true

    - name: Create service account token if not exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/service-account-token
          metadata:
            name: "{{ token_name }}"
            namespace: "{{ k8s_ns }}"
            annotations:
              kubernetes.io/service-account.name: "{{ service_account_name }}"
      when: existing_token.resources | length == 0

    - name: Get the service account token secret
      kubernetes.core.k8s_info:
        kubeconfig: "{{ master_kubeconfig }}"
        api_version: v1
        kind: Secret
        namespace: "{{ k8s_ns }}"
        name: "{{ token_name }}"
      register: sa_secrets
      no_log: true

    - name: Extract service account token
      ansible.builtin.set_fact:
        sa_token: >-
          {{
            (item.data.token | b64decode)
            if item.metadata.annotations['kubernetes.io/service-account.name'] == service_account_name
            else omit
          }}
      loop: "{{ sa_secrets.resources }}"
      when: "'kubernetes.io/service-account.name' in item.metadata.annotations"
      vars:
        service_account_secret: "{{ item }}"
      no_log: true

    - name: Set CERT token
      ansible.builtin.set_fact:
        CERT: "{% if cluster_env == 'p' %}{{ sa_secrets.resources[0].data['ca.crt'] }}\n{{ prod_ca }}{% else %}{{ sa_secrets.resources[0].data['ca.crt'] }}\n{{ nonProd_ca }}{% endif %}"

    - name: Extract cluster server URL
      ansible.builtin.set_fact:
        cluster_url: "{{  (kubeconfig_content | from_yaml).clusters[0].cluster['server'] }}"
      no_log: true

    - name: Set CA from master kubeconfig
      ansible.builtin.set_fact:
        cluster_CA: "{{ (kubeconfig_content | from_yaml).clusters[0].cluster['certificate-authority-data'] | b64decode }}"
      no_log: true

    - name: Ensure ClusterRole exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: "{{ cluster_role_name }}"
          rules:
            - apiGroups: ["*"]
              resources: ["*"]
              verbs: ["get", "list", "create", "update", "delete"]

    - name: Ensure Role exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: "{{ sa_role_name }}"
            namespace: "{{ k8s_ns }}"
          rules:
            - apiGroups: ["stork.libopenstorage.org"]
              resources: ["*"]
              verbs: ["*"]
            - apiGroups: ["*"]
              resources: ["*"]
              verbs: ["get", "list", "create", "update", "delete"]

    - name: Ensure ClusterRoleBinding exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: "{{ cluster_role_binding_name }}"
          subjects:
            - kind: ServiceAccount
              name: "{{ service_account_name }}"
              namespace: "{{ k8s_ns }}"
          roleRef:
            kind: ClusterRole
            name: "{{ cluster_role_name }}"
            apiGroup: rbac.authorization.k8s.io

    - name: Ensure RoleBinding exists
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ master_kubeconfig }}"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: "{{ sa_role_binding_name }}"
            namespace: "{{ k8s_ns }}"
          subjects:
            - kind: ServiceAccount
              name: "{{ service_account_name }}"
              namespace: "{{ k8s_ns }}"
          roleRef:
            kind: Role
            name: "{{ sa_role_name }}"
            apiGroup: rbac.authorization.k8s.io

    - name: Generate kubeconfig content
      ansible.builtin.set_fact:
        kubeconfig_content: |
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              certificate-authority-data: {{ CERT | b64encode }}
              server: {{ cluster_url }}
            name: kubernetes
          contexts:
          - context:
              cluster: kubernetes
              namespace: {{ k8s_ns }}
              user: {{ service_account_name }}
            name: {{ service_account_name }}-context
          current-context: {{ service_account_name }}-context
          users:
          - name: {{ service_account_name }}
            user:
              token: {{ sa_token }}
      no_log: true

    - name: Check if kubeconfig exists in Vault
      community.hashi_vault.vault_kv2_get:
        path: "secret/env/pxbackup/{{ cluster_name }}/{{ cluster_name }}.pxbkup"
        auth_method: token
      register: vault_check
      ignore_errors: true
      no_log: true
      vars:
        ansible_hashi_vault_namespace: ansible

    - name: Store kubeconfig in Vault
      community.hashi_vault.vault_kv2_write:
        path: "secret/env/pxbackup/{{ cluster_name }}/{{ cluster_name }}.pxbkup"
        data: "{{ existing_data | default({}) | combine({'kubeconfig': kubeconfig_content | b64encode}) }}"
        auth_method: token
      no_log: true
      vars:
        ansible_hashi_vault_namespace: ansible
        existing_data: "{{ vault_check.data.data if (vault_check.failed == false and vault_check.data is defined and vault_check.data.data is defined) else {} }}"

    - name: Print vault path and action
      ansible.builtin.debug:
        msg: "Kubeconfig {{ 'updated' if not vault_check.failed else 'created' }} in Vault at secret/env/pxbackup/{{ cluster_name }}/{{ cluster_name }}.pxbkup"
