---
- name: Parse Cluster Name
  hosts: localhost
  gather_facts: false
  vars:
    cluster_name: "eng-paas-d-eusw1a-4"
  tasks:
    - name: Set initial cluster facts
      ansible.builtin.set_fact:
        parts: "{{ cluster_name.split('-') }}"

    - name: Extract basic fields from cluster name
      ansible.builtin.set_fact:
        cluster_user: "{{ parts[0] }}"
        platform: "{{ parts[1] }}"
        cluster_env: "{{ parts[2] | regex_replace('p', 'prod') | regex_replace('d', 'dev') | regex_replace('t', 'test') }}"
        region_zone: "{{ parts[3] }}"
        cluster_id: "{{ parts[4] }}"

    - name: Extract region and zone
      ansible.builtin.set_fact:
        region: "{{ region_zone[:-1] }}"
        zone: "{{ region_zone[-1:] | regex_replace('a', 'zone-a') | regex_replace('b', 'zone-b') | regex_replace('c', 'zone-c') }}"

    - name: Debug facts
      ansible.builtin.debug:
        msg:
          - "cluster_user: {{ cluster_user }}"
          - "Platform: {{ platform }}"
          - "Environment: {{ cluster_env }}"
          - "Region: {{ region }}"
          - "Zone: {{ zone }}"
          - "Cluster ID: {{ cluster_id }}"
